# Uncomment this line to define a global platform for your project

platform :ios, '8.0'

# Uncomment this line if you're using Swift
use_frameworks!

target 'CocoapodsDemo' do
	pod 'JustApisSwiftSDK', :git => 'https://github.com/AnyPresence/justapis-swift-sdk.git'
end

